build:
  image: node
  commands:
    - npm install
    - npm run build:production
cache:
  mount:
    - node_modules
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys-ui
    tag: console
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: [staging,master]
deploy:
  ssh:
    host: 
      - staging.xiaolumm.com
    when:
      branch: [staging,master]
    user: root
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys-ui:console
      - docker run --rm -v /var/data:/data registry.aliyuncs.com/xiaolu-img/xiaolusys-ui:console cp -rf console /data/console
  ssh:
    host: 
      - euho.xiaolumm.com
    when:
      branch: euho
    user: root
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys-ui:console
      - docker run --rm -v /var/data:/data registry.aliyuncs.com/xiaolu-img/xiaolusys-ui:console cp -rf console /data/console
 